spring.config.import=optional:file:.env[.properties]

spring.application.name=finnew-api-gateway

#HEALTH MONITORING - ACTUATOR
management.endpoints.web.exposure.include=health, metric, info

server.port=8085
logging.level.org.springframework.cloud.gateway=TRACE

spring.security.user.name=disabled
spring.security.user.password=disabled

#JWT SECURITY CONFIG
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#EUREKA Discover
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/